[#4322] fix: python-client module import error
apache/gravitino pull request #4326
Opened 2024-07-31 14:25 UTC by xunliu

### What changes were proposed in this pull request?

Run gravitino python client integration test will occur tests module import error

### Why are the changes needed?

```
ImportError: Failed to import test module: test_schema
Traceback (most recent call last):
  File "/builds/no5LrKHc/0/streaming/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/builds/no5LrKHc/0/streaming/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/builds/no5LrKHc/0/streaming/gravitino/clients/client-python/tests/integration/test_schema.py", line 19, in <module>
    from tests.integration.integration_test_env import IntegrationTestEnv
ModuleNotFoundError: No module named 'tests'
```

Fix: #4322

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

CI Passed

2024-07-31 14:43 UTC, xunliu commented
hi @noidname01 Please help me review this PR, Thanks.

2024-07-31 15:46 UTC, noidname01 requested changes

2024-07-31 15:46 UTC, noidname01 commented on clients/client-python/tests/unittests/test_name_identifier.py
> -
Is this necessary?

2024-07-31 17:09 UTC, xunliu commented on clients/client-python/tests/unittests/test_name_identifier.py
> -
delete this line to trigger python CI

2024-07-31 17:14 UTC, noidname01 commented
I think we need to add a task to `build.gradle.kts` to add `client-python` path in either `PYTHONPATH` or `sys.path` to solve this problem locally.

2024-08-01 05:15 UTC, jerryshao approved these changes

2024-08-01 06:02 UTC, merged