[#4227] improvement(client-python): Add Catalog Error Handler and related exceptions, test cases in client-python
apache/gravitino pull request #4345
Opened 2024-08-03 15:45 UTC by jingjia88

### What changes were proposed in this pull request?

Add Catalog Error Handler and related exceptions, test cases in `client-python` based on `client-java`

### Why are the changes needed?

Fix: #4227 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

UT Added and test with `./gradlew client:client-python:test`

2024-08-05 10:39 UTC, xunliu commented
hi @noidname01 Please help review this PR, thanks!

2024-08-06 02:29 UTC, jerryshao commented
@jingjia88 would you please fix the conflicts?

2024-08-06 12:21 UTC, noidname01 requested changes
It seems that there are some problems when you solve the merge conflict, please remember to run test locally before every push.

2024-08-06 12:21 UTC, noidname01 commented on clients/client-python/tests/unittests/test_error_handler.py
> +                    CatalogAlreadyExistsException, "mock error"
There are two right parenthesis missing.

2024-08-06 12:21 UTC, noidname01 commented on clients/client-python/gravitino/exceptions/base.py
> +class NoSuchCatalogException(NotFoundException):
This class is redefined.

2024-08-06 13:36 UTC, jingjia88 commented
Finished~

2024-08-07 06:00 UTC, noidname01 requested changes
Except for the minor issue, LGTM.

2024-08-07 13:19 UTC, jingjia88 commented on clients/client-python/gravitino/exceptions/base.py
> +class CatalogAlreadyExistsException(AlreadyExistsException):
Done!

2024-08-08 15:57 UTC, noidname01 approved these changes

2024-08-09 02:16 UTC, jerryshao approved these changes

2024-08-09 05:43 UTC, mchades approved these changes
I'm going to merge this PR, thanks for your contributions!

2024-08-09 05:43 UTC, merged