[#5901] feat(core): support tag event to Gravitino server
apache/gravitino pull request #5998
Opened 2024-12-26 03:04 UTC by TungYuChiang

### What changes were proposed in this pull request?

1. Create corresponding event like ListTagEvent
2. Add corresponding event to TagEventDispatcher

### Why are the changes needed?

(Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.)

Fix: #5901 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

2024-12-26 03:16 UTC, orenccl requested changes

2024-12-26 03:16 UTC, orenccl commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
>        // TODO: getTagEvent
Redundant line?

2024-12-26 03:16 UTC, orenccl commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
>        // TODO: listMetadataObjectsForTagEvent
Redundant line?

2024-12-26 06:37 UTC, orenccl commented
It would be better to turn this PR into a draft before updating the unit tests.

2024-12-26 13:49 UTC, FANNG1 commented
will review the PR until #5944 is merged for some duplicated logic, please wait for a while.

2025-01-07 11:57 UTC, FANNG1 commented
@TungYuChiang could you rebase your code since #5944 is merged

2025-01-07 11:58 UTC, FANNG1 commented
cc @cool9850311

2025-01-08 03:25 UTC, TungYuChiang commented
> @TungYuChiang could you rebase your code since #5944 is merged

sure, I will complete it within the next few days.

2025-01-13 01:56 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(new ListTagEvent(PrincipalUtils.getCurrentUserName(), metalake));
could you rename ListTagsFailureEvent to ListTagFailureEvent to keep consistent with other list event?

2025-01-13 01:56 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
>            new ListTagsInfoFailureEvent(PrincipalUtils.getCurrentUserName(), metalake, e));
could you rename `ListTagsInfoFailureEvent` to `ListTagInfoFailureEvent` to keep consistent with other list event?

2025-01-13 01:57 UTC, FANNG1 commented
Event represents an specific operation to specific resource, the current implement pass `metalake` as resource name, this's not correct for some event, please refer to XXTagFailureEvent for the definition of the resource.

2025-01-13 02:00 UTC, FANNG1 commented
please update the document too

2025-01-15 02:19 UTC, FANNG1 commented
@TungYuChiang any progress? If this PR is merged these days, we could meet the 0.8 release.

2025-01-15 02:57 UTC, TungYuChiang commented
> @TungYuChiang any progress? If this PR is merged these days, we could meet the 0.8 release.

I’m sorry for the delay. I’ve been a bit busy these past few days, but I’ll finish it by tomorrow evening. 
Thank you for your patience

2025-01-15 11:14 UTC, FANNG1 commented
> > @TungYuChiang any progress? If this PR is merged these days, we could meet the 0.8 release.
> 
> @FANNG1 , I’m sorry for the delay. I’ve been a bit busy these past few days, but I’ll finish it by tomorrow evening. Thank you for your patience

no hurry, please take your time

2025-01-16 00:23 UTC, TungYuChiang commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(new ListTagEvent(PrincipalUtils.getCurrentUserName(), metalake));
> could you rename ListTagsFailureEvent to ListTagFailureEvent to keep consistent with other list event?

Would it be better to rename `ListTagEvent` to `ListTagsEvent`?

2025-01-16 09:11 UTC, TungYuChiang commented
@FANNG1, I have fixed everything except renaming `ListTagsInfoFailureEvent `to `ListTagInfoFailureEvent`

2025-01-19 08:43 UTC, TungYuChiang commented
> @FANNG1, I have fixed everything except renaming `ListTagsInfoFailureEvent `to `ListTagInfoFailureEvent`

2025-01-20 06:43 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/GetTagEvent.java
> +    super(user, NameIdentifier.of(metalake));
Please use `NameIdentifierUtil.ofTag(metalake, tagName)` as resourceIdentifier.

2025-01-20 06:46 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(
please create `TagInfo` and passing `TagInfo` to `GetTagEvent`

2025-01-20 06:59 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(
please use TagInfo

2025-01-20 07:00 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AlterTagEvent.java
> +    this.tagChanges = tagChanges;
Please use clone   
```
  this.tagChanges = tagChanges.clone();
```

2025-01-20 07:02 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AlterTagEvent.java
> +    super(user, NameIdentifier.of(metalake));
use `NameIdentifierUtil.ofTag(metalake, tagName)` as identifier

2025-01-20 07:03 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectEvent.java
> +    this.tagsToAdd = tagsToAdd;
use clone for `tagsToAdd` `tagsToRemove `  `associatedTags `

2025-01-20 07:05 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectEvent.java
> +    super(user, NameIdentifier.of(metalake));
please use `MetadataObjectUtil.toEntityIdent(metalake, metadataObject)` as identifier

2025-01-20 07:05 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectEvent.java
> +  public MetadataObject metadataObject() {
please remove this, duplicated with identifier

2025-01-20 07:06 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectEvent.java
> +  public String metalake() {
please remove this, duplicated with identifier

2025-01-20 07:08 UTC, FANNG1 commented
> Event represents an specific operation to specific resource, the current implement pass `metalake` as resource name, this's not correct for some event, please refer to XXTagFailureEvent for the definition of the resource.

@TungYuChiang , please refer to `XXTagFailureEvent` for the definition of the resource identifier, thx.

2025-01-21 04:36 UTC, TungYuChiang commented
> > Event represents an specific operation to specific resource, the current implement pass `metalake` as resource name, this's not correct for some event, please refer to XXTagFailureEvent for the definition of the resource.
> 
> @TungYuChiang , please refer to `XXTagFailureEvent` for the definition of the resource identifier, thx.

I will fix it in the next few days.

2025-02-05 03:29 UTC, TungYuChiang commented on core/src/main/java/org/apache/gravitino/listener/api/event/AlterTagEvent.java
> +    this.tagChanges = tagChanges;
Hi @FANNG1 ,

I noticed that you suggested using clone() for tagChanges, but I'm encountering some issues that seem to be related to this change. Could you please explain why using clone() is necessary in this case? It would help me better understand the reasoning behind it and troubleshoot the current problem.

Thanks!

2025-02-05 06:52 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AlterTagEvent.java
> +    this.tagChanges = tagChanges;
It's a better practice to make the object isolated in post event listeners to avoid listeners change the object.

2025-02-08 06:12 UTC, TungYuChiang commented
@FANNG1 I can't test TagIT locally. When you have time, could you please approve the workflow for me? Thanks!

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/AlterTagEvent.java
> +    this.tagChanges = tagChanges != null ? tagChanges.clone() : new TagChange[0];
keep tagChanges as null, we could add `@Nullable` anotation to `tagChanges` method.

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/GetTagEvent.java
> +
add an method to get `tagInfo`?

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +              PrincipalUtils.getCurrentUserName(), metalake, metadataObject, name, tagInfo));
remove `name` from `GetTagForMetadataObjectEvent`, since the tag name is included in tagInfo

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/GetTagForMetadataObjectEvent.java
> +  }
add an method to get tagInfo?

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsEvent.java
> +        NameIdentifierUtil.ofTag(
the identifier is `NameIdentifier.of(metalake)`

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsInfoEvent.java
> +    super(user, NameIdentifierUtil.ofTag(metalake, tags[0].name()));
the identifier is `NameIdentifier.of(metalake)`

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsInfoEvent.java
> +
please add method to get `tags`

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsInfoForMetadataObjectEvent.java
> +  }
please add method to get tags

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      Tag[] tags = dispatcher.listTagsInfoForMetadataObject(metalake, metadataObject);
please use tagInfo for the event

2025-02-10 01:21 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(
please use tagInfo for the event

2025-02-10 01:24 UTC, FANNG1 commented
Could you rebase the code, add tag related event(include tag failure event and tag pre event) to the document, https://github.com/apache/gravitino/blob/main/docs/gravitino-server-config.md#L112, thx

2025-02-13 02:29 UTC, TungYuChiang commented on core/src/main/java/org/apache/gravitino/listener/api/event/AlterTagEvent.java
> +    this.tagChanges = tagChanges != null ? tagChanges.clone() : new TagChange[0];
If we keep null, it will cause an error when calling tagChanges.clone()

2025-02-13 02:40 UTC, TungYuChiang commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(
I appreciate the guidance! I see that we are getting multiple tags from listTagsForMetadataObject. Should we instantiate a new TagInfo for each tag, like this?

`TagInfo[] tagInfos = new TagInfo[tags.length];
for (int i = 0; i < tags.length; i++) {
    tagInfos[i] = new TagInfo(tags[i], comment, properties);
}`

2025-02-14 05:04 UTC, TungYuChiang commented
> Could you rebase the code, add tag related event(include tag failure event and tag pre event) to the document, https://github.com/apache/gravitino/blob/main/docs/gravitino-server-config.md#L112, thx

@FANNG1 , I have completed the requested changes, and I have left a comment above.

2025-02-24 08:49 UTC, TungYuChiang commented
Hi @FANNG1 , just checking in to see if you have any thoughts on my question above. Let me know if there's anything I should adjust. Thanks!

2025-02-24 09:14 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(
After another though, seems we could didn't pass the specific tag or metadata objects for LIST events to keep consistent with other LIST events like `ListTableEvent` or `ListFilesetEvent`, WDYT?

2025-02-24 09:17 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      Tag[] tags = dispatcher.listTagsInfoForMetadataObject(metalake, metadataObject);
no need to pass tagInfo or tags to the event

2025-02-24 09:25 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListMetadataObjectsForTagEvent.java
> +      String user, String metalake, String tagName, MetadataObject[] metadataObjects) {
remove `metadataObjects`?

2025-02-24 09:26 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsEvent.java
> +  public ListTagsEvent(String user, String metalake, String[] tagNames) {
remove tagNames?

2025-02-24 09:27 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsForMetadataObjectEvent.java
> +      String user, String metalake, MetadataObject metadataObject, String[] tags) {
remove tags?

2025-02-24 09:27 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsInfoEvent.java
> +  public ListTagsInfoEvent(String user, String metalake, Tag[] tags) {
remove `tags`?

2025-02-24 09:28 UTC, FANNG1 commented on core/src/main/java/org/apache/gravitino/listener/api/event/ListTagsInfoForMetadataObjectEvent.java
> +  public ListTagsInfoForMetadataObjectEvent(
remove `tags`?

2025-02-24 11:41 UTC, TungYuChiang commented on core/src/main/java/org/apache/gravitino/listener/TagEventDispatcher.java
> +      eventBus.dispatchEvent(
That makes sense!  I'll update the implementation accordingly.

2025-02-24 12:41 UTC, TungYuChiang commented
@FANNG1 , Thank you for your review!
I've addressed all the comments.

2025-02-24 15:29 UTC, FANNG1 commented
LGTM, except two minor comments

2025-02-26 15:06 UTC, TungYuChiang commented on docs/gravitino-server-config.md
> +| Gravitino server tag operation       | `ListTagsPreEvent`, `ListTagsInfoPreEvent`, `CreateTagPreEvent`, `GetTagPreEvent`, `AlterTagPreEvent`, `DeleteTagPreEvent`, `ListMetadataObjectsForTagPreEvent
Sure! I've already made the change.

2025-03-03 01:39 UTC, FANNG1 approved these changes

2025-03-03 01:41 UTC, FANNG1 commented
@TungYuChiang , merged to main, thanks for your contribution, thanks @orenccl for your review!

2025-03-03 01:41 UTC, merged

2025-03-03 01:43 UTC, TungYuChiang commented
> @TungYuChiang , merged to main, thanks for your contribution, thanks @orenccl for your review!

Thanks for your review and help.